defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: blog_post

comments:
    provider: disqus
    account: timothyhinrichs

pages_list:
  Home: '/'
  About: '/about.html'
  Contributors: '/contributors.html'
  Feed: '/feed.xml'

name: Rule Your Cloud
description: Using declarative rules to manage the cloud

