defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: blog_post
      comments: True

comments:
    provider: disqus
    account: timothyhinrichs

pages_list:
  Home: '/'
  About: '/about.html'
  Contributors: '/contributors.html'

name: Rule Your Cloud
# name: Automating policy
# name: Cloud By Law
description: Using policy to manage the cloud

